// GENERATED FILE — do not edit by hand.
// Run `node scripts/gen-styles.mjs` after re-exporting styles from BeerSmith.
//
// 148 styles (BJCP 2015) as [name, category] pairs, sorted by
// category then name. Names and categories only: the export's F_S_DESCRIPTION
// is verbatim BJCP guideline prose and this repo is public.
//
// A recipe's style is still a free string — this is the picker's catalog, not a
// constraint. Imported or legacy names that aren't here (Slackers' own "NEIPA",
// say) stay exactly as they are; the Edit view offers them alongside the list.

const STYLE_PAIRS = [
  ["Alternative Grain Beer", "Alternative Fermentables Beer"],
  ["Alternative Sugar Beer", "Alternative Fermentables Beer"],
  ["American Amber Ale", "Amber and Brown American Beer"],
  ["American Brown Ale", "Amber and Brown American Beer"],
  ["California Common", "Amber and Brown American Beer"],
  ["Altbier", "Amber Bitter European Beer"],
  ["Amber Kellerbier", "Amber Bitter European Beer"],
  ["Pale Kellerbier", "Amber Bitter European Beer"],
  ["Vienna Lager", "Amber Bitter European Beer"],
  ["Dunkles Bock", "Amber Malty European Lager"],
  ["Märzen", "Amber Malty European Lager"],
  ["Rauchbier", "Amber Malty European Lager"],
  ["American Porter", "American Porter and Stout"],
  ["American Stout", "American Porter and Stout"],
  ["Imperial Stout", "American Porter and Stout"],
  ["Brett Beer", "American Wild Ale"],
  ["Mixed-Fermentation Sour Beer", "American Wild Ale"],
  ["Wild Specialty Beer", "American Wild Ale"],
  ["Belgian Pale Ale", "Belgian Ale"],
  ["Bière de Garde", "Belgian Ale"],
  ["Witbier", "Belgian Ale"],
  ["Best Bitter", "British Bitter"],
  ["Ordinary Bitter", "British Bitter"],
  ["Strong Bitter", "British Bitter"],
  ["British Brown Ale", "Brown British Beer"],
  ["Dark Mild", "Brown British Beer"],
  ["English Porter", "Brown British Beer"],
  ["Czech Amber Lager", "Czech Lager"],
  ["Czech Dark Lager", "Czech Lager"],
  ["Czech Pale Lager", "Czech Lager"],
  ["Czech Premium Pale Lager", "Czech Lager"],
  ["Foreign Extra Stout", "Dark British Beer"],
  ["Oatmeal Stout", "Dark British Beer"],
  ["Sweet Stout", "Dark British Beer"],
  ["Tropical Stout", "Dark British Beer"],
  ["Munich Dunkel", "Dark European Lager"],
  ["Schwarzbier", "Dark European Lager"],
  ["Berliner Weisse", "European Sour Ale"],
  ["Flanders Red Ale", "European Sour Ale"],
  ["Fruit Lambic", "European Sour Ale"],
  ["Gueuze", "European Sour Ale"],
  ["Lambic", "European Sour Ale"],
  ["Oud Bruin", "European Sour Ale"],
  ["Fruit and Spice Beer", "Fruit Beer"],
  ["Fruit Beer", "Fruit Beer"],
  ["Specialty Fruit Beer", "Fruit Beer"],
  ["Berry Mead", "Fruit Mead"],
  ["Cyser", "Fruit Mead"],
  ["Melomel", "Fruit Mead"],
  ["Pyment", "Fruit Mead"],
  ["Stone Fruit Mead", "Fruit Mead"],
  ["Dunkles Weissbier", "German Wheat Beer"],
  ["Weissbier", "German Wheat Beer"],
  ["Weizenbock", "German Wheat Beer"],
  ["Gose", "Historical Beer"],
  ["Historical Beer - Other", "Historical Beer"],
  ["Kentucky Common", "Historical Beer"],
  ["Lichtenhainer", "Historical Beer"],
  ["London Brown Ale", "Historical Beer"],
  ["Piwo Grodziskie", "Historical Beer"],
  ["Pre-Prohibition Lager", "Historical Beer"],
  ["Pre-Prohibition Porter", "Historical Beer"],
  ["Roggenbier", "Historical Beer"],
  ["Sahti", "Historical Beer"],
  ["International Amber Lager", "International Lager"],
  ["International Dark Lager", "International Lager"],
  ["International Pale Lager", "International Lager"],
  ["American IPA", "IPA"],
  ["Belgian IPA", "IPA"],
  ["Black IPA", "IPA"],
  ["Brown IPA", "IPA"],
  ["New England IPA", "IPA"],
  ["Red IPA", "IPA"],
  ["Rye IPA", "IPA"],
  ["Specialty IPA", "IPA"],
  ["White IPA", "IPA"],
  ["Irish Extra Stout", "Irish Beer"],
  ["Irish Red Ale", "Irish Beer"],
  ["Irish Stout", "Irish Beer"],
  ["American Pale Ale", "Pale American Ale"],
  ["Blonde Ale", "Pale American Ale"],
  ["German Helles Exportbier", "Pale Bitter European Beer"],
  ["German Leichtbier", "Pale Bitter European Beer"],
  ["German Pils", "Pale Bitter European Beer"],
  ["Kölsch", "Pale Bitter European Beer"],
  ["Australian Sparkling Ale", "Pale Commonwealth Beer"],
  ["British Golden Ale", "Pale Commonwealth Beer"],
  ["English IPA", "Pale Commonwealth Beer"],
  ["Festbier", "Pale Malty European Lager"],
  ["Helles Bock", "Pale Malty European Lager"],
  ["Munich Helles", "Pale Malty European Lager"],
  ["Catharina Sour", "Provisional"],
  ["New Zealand Pilsner", "Provisional"],
  ["Scottish Export", "Scottish Ale"],
  ["Scottish Heavy", "Scottish Ale"],
  ["Scottish Light", "Scottish Ale"],
  ["Classic Style Smoked Beer", "Smoked Beer"],
  ["Specialty Smoked Beer", "Smoked Beer"],
  ["Clone Beer", "Specialty Beer"],
  ["Experimental Beer", "Specialty Beer"],
  ["Mixed Style Beer", "Specialty Beer"],
  ["Applewine", "Specialty Cider and Perry"],
  ["Cider with Herbs/Spices", "Specialty Cider and Perry"],
  ["Cider With Other Fruit", "Specialty Cider and Perry"],
  ["Ice Cider", "Specialty Cider and Perry"],
  ["New England Cider", "Specialty Cider and Perry"],
  ["Specialty Cider/Perry", "Specialty Cider and Perry"],
  ["Braggot", "Specialty Mead"],
  ["Experimental Mead", "Specialty Mead"],
  ["Historical Mead", "Specialty Mead"],
  ["Autumn Seasonal Beer", "Spiced Beer"],
  ["Spice, Herb or Vegetable Beer", "Spiced Beer"],
  ["Winter Seasonal Beer", "Spiced Beer"],
  ["Fruit and Spice Mead", "Spiced Mead"],
  ["Spice, Herb Or Vegetable Mead", "Spiced Mead"],
  ["American Lager", "Standard American Beer"],
  ["American Light Lager", "Standard American Beer"],
  ["American Wheat Beer", "Standard American Beer"],
  ["Cream Ale", "Standard American Beer"],
  ["English Cider", "Standard Cider and Perry"],
  ["French Cider", "Standard Cider and Perry"],
  ["New World Cider", "Standard Cider and Perry"],
  ["New World Perry", "Standard Cider and Perry"],
  ["Traditional Perry", "Standard Cider and Perry"],
  ["American Barleywine", "Strong American Ale"],
  ["American Strong Ale", "Strong American Ale"],
  ["Double IPA", "Strong American Ale"],
  ["Wheatwine", "Strong American Ale"],
  ["Belgian Blond Ale", "Strong Belgian Ale"],
  ["Belgian Golden Strong Ale", "Strong Belgian Ale"],
  ["Saison", "Strong Belgian Ale"],
  ["British Strong Ale", "Strong British Ale"],
  ["Burton Ale", "Strong British Ale"],
  ["English Barleywine", "Strong British Ale"],
  ["Old Ale", "Strong British Ale"],
  ["Wee Heavy", "Strong British Ale"],
  ["Baltic Porter", "Strong European Beer"],
  ["Doppelbock", "Strong European Beer"],
  ["Eisbock", "Strong European Beer"],
  ["Dry Mead", "Traditional Mead"],
  ["Semi-Sweet Mead", "Traditional Mead"],
  ["Sweet Mead", "Traditional Mead"],
  ["Belgian Dark Strong Ale", "Trappist Ale"],
  ["Belgian Dubbel", "Trappist Ale"],
  ["Belgian Tripel", "Trappist Ale"],
  ["Trappist Single", "Trappist Ale"],
  ["Specialty Wood-Aged Beer", "Wood Beer"],
  ["Wood-Aged Beer", "Wood Beer"],
];

// Flat name list, for membership checks.
export const styleNames = STYLE_PAIRS.map(([name]) => name);

// [{ category, names[] }] in catalog order — the shape an <optgroup> list wants.
export const stylesByCategory = STYLE_PAIRS.reduce((groups, [name, category]) => {
  const last = groups[groups.length - 1];
  if (last && last.category === category) last.names.push(name);
  else groups.push({ category, names: [name] });
  return groups;
}, []);
