-- Migration 0002: brew-day recipe data — TOMBSTONE
--
-- This version is recorded as applied in the remote migration history, so the
-- file must exist (supabase db push errors on a remote version with no local
-- file), but its body has been intentionally removed.
--
-- It originally seeded/overwrote the 18 preset recipes' ingredient rows and
-- mash temps from an April 2026 BeerSmith snapshot, and was written as
-- "re-runnable". On 2026-07-14 the first CI-driven `supabase db push` re-ran
-- it against production (migration history hadn't been baselined yet),
-- reverting any in-app recipe edits made since the original hand-run. The
-- destructive SQL is removed so no history repair or re-baseline can ever
-- replay it. Original contents are in git history if needed.
--
-- The production database is the source of truth for recipe data; fresh
-- environments get recipes via the in-app JSON import/backup, not migrations.
-- Convention going forward: data migrations must be write-once — never
-- "re-runnable" statements that overwrite user-editable rows.
